
//silver_chain_scope_start
//DONT MODIFY THIS COMMENT
//this import is computationally generated
//mannaged by SilverChain: https://github.com/OUIsolutions/SilverChain
#include "../imports/imports.typesH.h"
//silver_chain_scope_end

#define  BEARSSL_HTTPS_FAILT_TO_START_UNISOCKET 1
#define  BEARSSL_HTTPS_INVALID_URL 2
#define BEARSSL_HTTPS_IMPOSSIBLE_TO_OPEN_FILE 3
#define  BEARSSL_HTTPS_MUST_BE_IPV4 4
#define BEARSSL_HTTPS_BODY_ITS_BINARY 5
#define BEARSSL_HTTPS_IMPOSSIBLE_TO_READ_BODY 6
#define BEARSSL_HTTPS_BODY_SIZE_ITS_BIGGER_THAN_LIMIT 7
#define BEARSSL_HTTPS_ALOCATION_FAILED 8
#define BEARSSL_HTTPS_BODY_ITS_NOT_A_VALID_JSON 9
#define BEARSSL_HTTPS_FAILT_TO_CREATE_DNS_REQUEST 10
#define BEARSSL_HTTPS_NO_DNS_PROVIDED 11
#define BEARSSL_HTTPS_FAILT_TO_CREATE_SOCKET 12
#define BEARSSL_HTTPS_INVALID_IPV4 12
#define BEARSSL_HTTPS_FAILT_TO_CONNECT 13
#define BEARSSL_HTTPS_UNKNOW_ERROR 14
#define BEARSSL_HTTPS_INVALID_READ_CODE 15
#define BEARSSL_HTTPS_INVALID_HTTP_RESPONSE 16
#define BEARSSL_HTTPS_IMPOSSIBLE_TO_SEND_DATA 17